### ISSUE TITLE
Great Library

### ISSUE THREAD

**Issue by reduxdj** [zxbodya/reactive-widgets#1]
How do I compile and build this to run on a client app without the server? Can you provide an example?

**Comment by zxbodya** [comment]
You mean how to run it without server-side rendering? - you can disable it, by changing `$prerender->isEnabled` to false, if you do so - you will not need to run prerender server.

**Comment by reduxdj** [comment]
Oh no, I figured it out, I saw that you had a bower install. good to know about prerender in the future.
